import "reflect-metadata";
import { APIGatewayProxyEventV2, APIGatewayProxyStructuredResultV2 } from "aws-lambda";
import { LoggerServiceInterface } from "@yac/util/src/services/logger.service";
import { generateInternalServerErrorResponse } from "@yac/util/src/util/internalServerError.response.generator";
import { container } from "../inversion-of-control/container";
import { TYPES } from "../inversion-of-control/types";
import { CalendarControllerInterface } from "../controllers/calendar.controller";

const calendarController = container.get<CalendarControllerInterface>(TYPES.CalendarControllerInterface);
const loggerService = container.get<LoggerServiceInterface>(TYPES.LoggerServiceInterface);

export const handler = async (event: APIGatewayProxyEventV2): Promise<APIGatewayProxyStructuredResultV2> => {
  try {
    loggerService.trace("completeGoogleAccessFlow called", { event }, "completeGoogleAccessFlow handler");

    const response = await calendarController.completeGoogleAccessFlow(event);

    return response;
  } catch (error: unknown) {
    // We should never get here, as Controller classes should never throw, but if for some reason we do, we need to log it
    loggerService.error("Catastrophic error in completeGoogleAccessFlow handler", { error, event }, "completeGoogleAccessFlow handler");

    return generateInternalServerErrorResponse(error);
  }
};
